language: go

go:
    - 1.6

services:
    - mysql
    - redis-serveri
    - elasticsearch
    - mongodb

env:
    - DOCKER_BIND_LOCALHOST=true

before_script:
    - sleep 10
    - mysql -u root -e 'create database CurtData;'

build:
    - setup-go-workspace

    - script:
        name: go get
        code: |
            go get -v github.com/golang/lint/golint
            go get -d -t -v ./...

    - script:
        name: go build
        code: |
            go build -v

    - script:
        name: go test ./...
        code: |
            go test -v ./models/geography
            go vet ./...
            golint ./...
