language: go

go:
    - 1.6

sudo: required

services:
    - docker

before_install:
    - docker pull mysql
    - docker pull mongo
    - docker pull redis
    - docker pull elasticsearch

build:
    - setup-go-workspace

    - script:
        name: go get
        code: |
            go get -v github.com/golang/lint/golint
            go get -d -t -v ./...

    - script:
        name: go build
        code: |
            go build -v

    - script:
        name: go test ./...
        code: |
            go test -v ./models/geography
            go vet ./...
            golint ./...
